### ISSUE TITLE
CTCF binding sites

### ISSUE THREAD

**Issue by sunhuimin123** [lucananni93/CTCF_Spatial_Patterns#2]
您好，请问您的原始数据及最终数据集可以提供吗？非常感谢，期待您的回复！

**Comment by lucananni93** [comment]
Can you please write your question in english?

**Comment by sunhuimin123** [comment]
I want to try to be a cluster of CTCF. I refer to your paper in the direction of CTCF. Can you provide the original data?  thank you！

**Comment by sunhuimin123** [comment]
I'm glad to hear from you

**Comment by lucananni93** [comment]
As explained in the paper, the CTCF collection that we used is available as Supplementary Table 1: https://static-content.springer.com/esm/art%3A10.1186%2Fs13059-020-02108-x/MediaObjects/13059_2020_2108_MOESM2_ESM.xlsx

**Comment by sunhuimin123** [comment]
thank you！
